mode: test
phase: completion

batch_size: 4

data:
  dataset: 'datasets'
  num_point: 80000
  num_target: 256
  ap_iou_thresholds: [0.5]
  dump_threshold: 0.5
  conf_thresh: 0.05
  nms_iou: 0.25
  cluster_sampling: seed_fps
  remove_empty_box: false
  use_3d_nms: true
  use_old_type_nms: false
  cls_nms: true
  per_class_proposal: true
  use_cls_for_completion: false

generation:
  evaluate_mesh_mAP: false
  export_shape: false
  generate_mesh: false
  dump_results: false